function [ time, runoff, cumulativeRunoff ] = importOutFile( outFileName )
%IMPORTOUTFILE imports a .out file generated by HYDRUS and returns the Runoff
delimiterIn = ' ';
headerlinesIn = 9;
A = importdata(outFileName,delimiterIn,headerlinesIn);
time = A.data(:,1);
runoff = A.data(:,15);
cumulativeRunoff = A.data(:,16);
end
