function [TIMESTAMP,RECORD,SEVolt,SEVolt2,SEVolt3,SEVolt4,SEVolt5,SEVolt6,SEVolt7,SEVolt8,SEVolt9,SEVolt10,SEVolt11,SEVolt12] = importSMFile(filename, startRow, endRow)
%importSMFile Import numeric data from a text file as column vectors.
%   [TIMESTAMP,RECORD,SEVOLT,SEVOLT2,SEVOLT3,SEVOLT4,SEVOLT5,SEVOLT6,SEVOLT7,SEVOLT8,SEVOLT9,SEVOLT10,SEVOLT11,SEVOLT12]
%   = importSMFile(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TIMESTAMP,RECORD,SEVOLT,SEVOLT2,SEVOLT3,SEVOLT4,SEVOLT5,SEVOLT6,SEVOLT7,SEVOLT8,SEVOLT9,SEVOLT10,SEVOLT11,SEVOLT12]
%   = importSMFile(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [TIMESTAMP,RECORD,SEVolt,SEVolt2,SEVolt3,SEVolt4,SEVolt5,SEVolt6,SEVolt7,SEVolt8,SEVolt9,SEVolt10,SEVolt11,SEVolt12] = importSMFile('3755SM_Raw1.csv',5, 28512);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/03/06 08:32:23

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 5;
    endRow = inf;
end

%% Format for each line of text:
%   column1: datetimes (%{yyyy-MM-dd HH:mm:ss}D)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{yyyy-MM-dd HH:mm:ss}D%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
TIMESTAMP = dataArray{:, 1};
RECORD = dataArray{:, 2};
SEVolt = dataArray{:, 3};
SEVolt2 = dataArray{:, 4};
SEVolt3 = dataArray{:, 5};
SEVolt4 = dataArray{:, 6};
SEVolt5 = dataArray{:, 7};
SEVolt6 = dataArray{:, 8};
SEVolt7 = dataArray{:, 9};
SEVolt8 = dataArray{:, 10};
SEVolt9 = dataArray{:, 11};
SEVolt10 = dataArray{:, 12};
SEVolt11 = dataArray{:, 13};
SEVolt12 = dataArray{:, 14};

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% TIMESTAMP=datenum(TIMESTAMP);


